# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-12-14 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.DateField()),
                ('loc', models.CharField(max_length=50)),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
    ]
